// flow-typed signature: 1b5fa63b121a033f28a486bc4f16a0af
// flow-typed version: <<STUB>>/react-native_v0.51.x/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare module.exports: any;
}
